apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks-demo
spec:
  selector:
    matchLabels:
      app: ctse-assignment-user-management
  template:
    metadata:
      labels:
        app: ctse-assignment-user-management
    spec:
      containers:
        - name: ctse-assignment-user-management
          image: salithaekanayaka/ctse-assignment-user-management
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080